import {
  Rocket,
  Zap,
  Star,
  Heart,
  Sparkles,
  Target,
  Flame,
  Sun,
  Lightbulb,
  Trophy,
  Medal,
  Crown,
  Gem,
  Gift,
  Database,
  Server,
  Cloud,
  Cpu,
  Brain,
  Code,
  GitBranch,
  Terminal,
  Network,
  Share2,
  Layers,
  Boxes,
  HardDrive,
  Binary,
  ChartColumn,
  ChartLine,
  ChartPie,
  Activity,
  TrendingUp,
  Gauge,
  Table,
  FileText,
  Workflow,
  GitFork,
  CircleCheck,
  CircleAlert,
  TriangleAlert,
  Info,
  CircleHelp,
  Ban,
  Clock,
  Calendar,
  Hourglass,
  Loader,
  RefreshCw,
  Repeat,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  Shield,
  ShieldCheck,
  Lock,
  Unlock,
  Key,
  Fingerprint,
  Eye,
  EyeOff,
  Scan,
  UserCheck,
  User,
  Users,
  UserRound,
  MessageSquare,
  Mail,
  Phone,
  Handshake,
  Stethoscope,
  Microscope,
  Pill,
  Syringe,
  Hospital,
  Dna,
  DollarSign,
  Euro,
  PoundSterling,
  CreditCard,
  Wallet,
  Briefcase,
  Building2,
  Factory,
  Truck,
  ShoppingCart,
  Calculator,
  Receipt,
  Percent,
  Scale,
  BookOpen,
  GraduationCap,
  Quote,
  Search,
  Filter,
  Settings,
  Wrench,
  Hammer,
  Bug,
  List,
  Grid3x3,
  Link,
  Paperclip,
  Bell,
  Flag,
  ThumbsUp,
  ThumbsDown,
  Smile,
  PartyPopper,
  Trash2,
  Download,
  Upload,
  Play,
  Pause,
  Plus,
  Check,
  Menu,
  Home,
  MapPin,
  Compass,
  Navigation,
  Route,
  Map,
  Globe,
  Pencil,
  Keyboard,
  Expand,
  LayoutGrid,
  Wand,
  Palette,
  MoveRight,
  ArrowUpRight,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * The icons a markdown file may reference with `:name:`.
 *
 * Deliberately a curated allow-list rather than all of lucide: `lucide-react/dynamic`
 * pulls a map of 2000+ dynamic-import thunks into the main chunk (+34 kB gzip and
 * ~1800 extra files in `dist/`) for the handful of icons a deck actually uses.
 * These static imports stay tree-shaken; the current list costs ~13 kB gzip.
 *
 * Keys are the kebab-case name used in markdown. To add an icon, append it to
 * both lists below using its name at lucide.dev/icons. Unknown names are left
 * as literal text rather than dropped, so a typo never eats content.
 */
export const ICON_MAP = {
  'rocket': Rocket,
  'zap': Zap,
  'star': Star,
  'heart': Heart,
  'sparkles': Sparkles,
  'target': Target,
  'flame': Flame,
  'sun': Sun,
  'lightbulb': Lightbulb,
  'trophy': Trophy,
  'medal': Medal,
  'crown': Crown,
  'gem': Gem,
  'gift': Gift,
  'database': Database,
  'server': Server,
  'cloud': Cloud,
  'cpu': Cpu,
  'brain': Brain,
  'code': Code,
  'git-branch': GitBranch,
  'terminal': Terminal,
  'network': Network,
  'share-2': Share2,
  'layers': Layers,
  'boxes': Boxes,
  'hard-drive': HardDrive,
  'binary': Binary,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'activity': Activity,
  'trending-up': TrendingUp,
  'gauge': Gauge,
  'table': Table,
  'file-text': FileText,
  'workflow': Workflow,
  'git-fork': GitFork,
  'circle-check': CircleCheck,
  'circle-alert': CircleAlert,
  'triangle-alert': TriangleAlert,
  'info': Info,
  'circle-help': CircleHelp,
  'ban': Ban,
  'clock': Clock,
  'calendar': Calendar,
  'hourglass': Hourglass,
  'loader': Loader,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'chevron-right': ChevronRight,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'fingerprint': Fingerprint,
  'eye': Eye,
  'eye-off': EyeOff,
  'scan': Scan,
  'user-check': UserCheck,
  'user': User,
  'users': Users,
  'user-round': UserRound,
  'message-square': MessageSquare,
  'mail': Mail,
  'phone': Phone,
  'handshake': Handshake,
  'stethoscope': Stethoscope,
  'microscope': Microscope,
  'pill': Pill,
  'syringe': Syringe,
  'hospital': Hospital,
  'dna': Dna,
  'dollar-sign': DollarSign,
  'euro': Euro,
  'pound-sterling': PoundSterling,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'briefcase': Briefcase,
  'building-2': Building2,
  'factory': Factory,
  'truck': Truck,
  'shopping-cart': ShoppingCart,
  'calculator': Calculator,
  'receipt': Receipt,
  'percent': Percent,
  'scale': Scale,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'quote': Quote,
  'search': Search,
  'filter': Filter,
  'settings': Settings,
  'wrench': Wrench,
  'hammer': Hammer,
  'bug': Bug,
  'list': List,
  'grid-3x3': Grid3x3,
  'link': Link,
  'paperclip': Paperclip,
  'bell': Bell,
  'flag': Flag,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'smile': Smile,
  'party-popper': PartyPopper,
  'trash-2': Trash2,
  'download': Download,
  'upload': Upload,
  'play': Play,
  'pause': Pause,
  'plus': Plus,
  'check': Check,
  'menu': Menu,
  'home': Home,
  'map-pin': MapPin,
  'compass': Compass,
  'navigation': Navigation,
  'route': Route,
  'map': Map,
  'globe': Globe,
  'pencil': Pencil,
  'keyboard': Keyboard,
  'expand': Expand,
  'layout-grid': LayoutGrid,
  'wand': Wand,
  'palette': Palette,
  'move-right': MoveRight,
  'arrow-up-right': ArrowUpRight,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICON_MAP

export const ICON_NAMES: readonly IconName[] = Object.keys(ICON_MAP) as IconName[]

export function getIcon(name: string): LucideIcon | undefined {
  return Object.hasOwn(ICON_MAP, name) ? ICON_MAP[name as IconName] : undefined
}
